### ISSUE TITLE
Could you set the install to resolve localhost instead of the ip?

### ISSUE THREAD

**Issue by jhollender** [r-baker/simple-magento-vagrant#15]
Is it pretty easy to change the bash script to make the magento vm resolve on localhost:8080 instead of 127.0.0.1:8080?

**Comment by r-baker** [comment]
You can try it. Just replace 127.0.0.1 with localhost. From memory, you will experience issues. Some browsers, (and possibly magento itself) are fussy about cookies set for `localhost`, rather than a proper ".tld" domain name, or an IP.

With Vagrant, you're better off adding an entry to your host machine's `hosts` file and pointing this to 127.0.0.1. e.g.
`magento.dev    127.0.0.1`

Then adjust the `bootstrap.sh` script to install Magento using your chosen domain.

**Comment by jhollender** [comment]
I tried that, but whenever I access the store by magento.localhost on my host machine, Magento redirects to 127.0.0.1

**Comment by r-baker** [comment]
It shouldn't if you update the Magento install options with:

    --url "http://magento.localhost:8080/"
    --secure_base_url "http://magento.localhost:8080/"

Then update your hosts file accordingly.
