### ISSUE TITLE
Offline capabilites

### ISSUE THREAD

**Issue by joh-klein** [r-baker/simple-magento-vagrant#18]
What do you think of adding a "bin" folder and looking in there, if the desired archive/binary is already there and using that? (And if not present, download it into that folder for future use)
Would make it more portable and easier to use in places with spotty coverage.

**Comment by r-baker** [comment]
Yes, that's a good idea. I have already done this for the sample data download as it's pretty huge: https://github.com/r-baker/simple-magento-vagrant/blob/master/bootstrap.sh#l82 

Perhaps we could implement something similar here: https://github.com/r-baker/simple-magento-vagrant/blob/master/bootstrap.sh#l68.

I'd prefer it if there .tar was just dropped into the project root so that it's really easy to use.

**Comment by joh-klein** [comment]
The upside of having a dedicated folder are in my opinion: you can keep not only the huge tars but also the small scripts (n98-magerun and modman) in there and is all nice and tidy :)

Maybe a different folder name would make it clearer and thus equally simple to use?

The PR from kojiromike does something like this already, although it is not super easy and straight forward.

**Comment by r-baker** [comment]
Yeah, that sounds reasonable.

To keep things simple, I like the idea of the provisioning script working out of the box, without configuration. So any checks for user-provided Magento .tar files should fall back to existing behaviour.

**Comment by joh-klein** [comment]
I think we should not reinvent the wheel in this case and just use the install option that comes along with n98-magerun. It has a way to use local files as well. The only "difficult" part is the appropriate yaml file.
