### ISSUE TITLE
How to change 127.0.0.1:8080 to customdomain.dev?

### ISSUE THREAD

**Issue by ravbetsky** [r-baker/simple-magento-vagrant#22]
Hi!

May be it's a stupid question, but i couldn't change it... Can you help?

**Comment by r-baker** [comment]
You'll need to add an entry to your host machine's hosts file to resolve to the Vagrant machine IP. On linux/mac this is `/etc/hosts` Windows `Windows/System32/drivers/etc/hosts`

Then update the bootstrap.sh script and replace 127.0.0.1 with `customdomain.dev` so that your Magento store installs using that domain.

**Comment by ravbetsky** [comment]
Thanks!

But I still need to enter port number, so `customdomain.dev` is not working for me, but `customdomain.dev:8080` is OK. How this can be resolved?

**Comment by r-baker** [comment]
Update your hosts file as above. No need to specify the port number (80 is default).

Update the Vagrantfile config to `config.vm.network :forwarded_port, guest: 80, host: 80`: https://github.com/r-baker/simple-magento-vagrant/blob/master/Vagrantfile#l20

Then update Magento config to use `http://customdomain.dev`: https://github.com/r-baker/simple-magento-vagrant/blob/master/bootstrap.sh#l105-106

You might need to update the following lines to use port 80 (i'm not 100% sure without testing myself): https://github.com/r-baker/simple-magento-vagrant/blob/master/bootstrap.sh#l29-30

**Comment by davidtaboas** [comment]
You can use a proxy server. Some utilities are [Pow for OSX](https://github.com/basecamp/pow) or [Prax for Linux](https://github.com/ysbaddaden/prax).
